default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: jojo
  password: mdproot
  host: localhost

development:
  <<: *default
  database: gossip_db_dev

test:
  <<: *default
  database: gossip_db_test

production:
  <<: *default
  database: gossip_db
